# Generated by Django 5.0.3 on 2024-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Events", "0003_event_isclosed_alter_event_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="isClosed",
            field=models.BooleanField(default=False, verbose_name="Kapalı"),
        ),
    ]
